// https://json-to-js.com/

export const mockRelease: releaseData[] = [
    {
        url: 'https://api.github.com/repos/Pidsamhai/release_file_test/releases/24910571',
        assets_url: 'https://api.github.com/repos/Pidsamhai/release_file_test/releases/24910571/assets',
        upload_url: 'https://uploads.github.com/repos/Pidsamhai/release_file_test/releases/24910571/assets{?name,label}',
        html_url: 'https://github.com/Pidsamhai/release_file_test/releases/tag/v1.0-beta',
        id: 24910571,
        node_id: 'MDc6UmVsZWFzZTI0OTEwNTcx',
        tag_name: 'v1.0-beta',
        target_commitish: 'master',
        name: 'v1.0-beta',
        draft: false,
        author: {
            login: 'mengxyz',
            id: 36928202,
            node_id: 'MDQ6VXNlcjM2OTI4MjAy',
            avatar_url: 'https://avatars3.githubusercontent.com/u/36928202?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/mengxyz',
            html_url: 'https://github.com/mengxyz',
            followers_url: 'https://api.github.com/users/mengxyz/followers',
            following_url: 'https://api.github.com/users/mengxyz/following{/other_user}',
            gists_url: 'https://api.github.com/users/mengxyz/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/mengxyz/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/mengxyz/subscriptions',
            organizations_url: 'https://api.github.com/users/mengxyz/orgs',
            repos_url: 'https://api.github.com/users/mengxyz/repos',
            events_url: 'https://api.github.com/users/mengxyz/events{/privacy}',
            received_events_url: 'https://api.github.com/users/mengxyz/received_events',
            type: 'User',
            site_admin: false
        },
        prerelease: false,
        created_at: '2020-03-26T21:38:07Z',
        published_at: '2020-03-26T21:42:13Z',
        assets: [
            {
                url: 'https://api.github.com/repos/Pidsamhai/release_file_test/releases/assets/19043163',
                id: 19043163,
                node_id: 'MDEyOlJlbGVhc2VBc3NldDE5MDQzMTYz',
                name: 'app-debug.apk',
                label: null,
                uploader: {
                    login: 'mengxyz',
                    id: 36928202,
                    node_id: 'MDQ6VXNlcjM2OTI4MjAy',
                    avatar_url: 'https://avatars3.githubusercontent.com/u/36928202?v=4',
                    gravatar_id: '',
                    url: 'https://api.github.com/users/mengxyz',
                    html_url: 'https://github.com/mengxyz',
                    followers_url: 'https://api.github.com/users/mengxyz/followers',
                    following_url: 'https://api.github.com/users/mengxyz/following{/other_user}',
                    gists_url: 'https://api.github.com/users/mengxyz/gists{/gist_id}',
                    starred_url: 'https://api.github.com/users/mengxyz/starred{/owner}{/repo}',
                    subscriptions_url: 'https://api.github.com/users/mengxyz/subscriptions',
                    organizations_url: 'https://api.github.com/users/mengxyz/orgs',
                    repos_url: 'https://api.github.com/users/mengxyz/repos',
                    events_url: 'https://api.github.com/users/mengxyz/events{/privacy}',
                    received_events_url: 'https://api.github.com/users/mengxyz/received_events',
                    type: 'User',
                    site_admin: false
                },
                content_type: 'application/vnd.android.package-archive',
                state: 'uploaded',
                size: 4316508,
                download_count: 30,
                created_at: '2020-03-26T21:41:44Z',
                updated_at: '2020-03-26T21:41:59Z',
                browser_download_url: 'https://github.com/Pidsamhai/release_file_test/releases/download/v1.0-beta/app-debug.apk'
            },
            {
                url: 'https://api.github.com/repos/Pidsamhai/release_file_test/releases/assets/19093106',
                id: 19093106,
                node_id: 'MDEyOlJlbGVhc2VBc3NldDE5MDkzMTA2',
                name: 'checksum.md5',
                label: null,
                uploader: {
                    login: 'mengxyz',
                    id: 36928202,
                    node_id: 'MDQ6VXNlcjM2OTI4MjAy',
                    avatar_url: 'https://avatars3.githubusercontent.com/u/36928202?v=4',
                    gravatar_id: '',
                    url: 'https://api.github.com/users/mengxyz',
                    html_url: 'https://github.com/mengxyz',
                    followers_url: 'https://api.github.com/users/mengxyz/followers',
                    following_url: 'https://api.github.com/users/mengxyz/following{/other_user}',
                    gists_url: 'https://api.github.com/users/mengxyz/gists{/gist_id}',
                    starred_url: 'https://api.github.com/users/mengxyz/starred{/owner}{/repo}',
                    subscriptions_url: 'https://api.github.com/users/mengxyz/subscriptions',
                    organizations_url: 'https://api.github.com/users/mengxyz/orgs',
                    repos_url: 'https://api.github.com/users/mengxyz/repos',
                    events_url: 'https://api.github.com/users/mengxyz/events{/privacy}',
                    received_events_url: 'https://api.github.com/users/mengxyz/received_events',
                    type: 'User',
                    site_admin: false
                },
                content_type: 'application/octet-stream',
                state: 'uploaded',
                size: 33,
                download_count: 11,
                created_at: '2020-03-28T18:48:55Z',
                updated_at: '2020-03-28T18:48:58Z',
                browser_download_url: 'https://github.com/Pidsamhai/release_file_test/releases/download/v1.0-beta/checksum.md5'
            }
        ],
        tarball_url: 'https://api.github.com/repos/Pidsamhai/release_file_test/tarball/v1.0-beta',
        zipball_url: 'https://api.github.com/repos/Pidsamhai/release_file_test/zipball/v1.0-beta',
        body: '- Update A\r\n- Update B\r\n- Update C'
    }
]

interface releaseData {
    url: string,
    assets_url: string,
    upload_url: string,
    html_url: string,
    id: number,
    node_id: string,
    tag_name: string,
    target_commitish: string,
    name: string,
    draft: boolean,
    author: author,
    prerelease: boolean,
    created_at: string,
    published_at: string,
    assets: assets[],
    tarball_url: string,
    zipball_url: string,
    body: string
}

interface author {
    login: string,
    id: number,
    node_id: string,
    avatar_url: string,
    gravatar_id: string,
    url: string,
    html_url: string,
    followers_url: string,
    following_url: string,
    gists_url: string,
    starred_url: string,
    subscriptions_url: string,
    organizations_url: string,
    repos_url: string,
    events_url: string,
    received_events_url: string,
    type: string,
    site_admin: boolean
}

interface assets {
    url: string,
    id: number,
    node_id: string,
    name: string,
    label: string | null,
    uploader: {
        login: string,
        id: number,
        node_id: string,
        avatar_url: string,
        gravatar_id: string,
        url: string,
        html_url: string,
        followers_url: string,
        following_url: string,
        gists_url: string,
        starred_url: string,
        subscriptions_url: string,
        organizations_url: string,
        repos_url: string,
        events_url: string,
        received_events_url: string,
        type: string,
        site_admin: boolean
    },
    content_type: string,
    state: string,
    size: number,
    download_count: number,
    created_at: string,
    updated_at: string,
    browser_download_url: string
}